services:
  web-anno:
    image: ghcr.io/asano69/web-anno:latest
    container_name: web-anno
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - web-anno.env
    volumes:
      - ./data:/web-anno/data
        #- /etc/ssl/certs/root_ca.crt:/certs/root_ca.crt:ro # optional
    environment:
      - TZ=Etc/UTC
      #
      - WEB-ANNO_SERVER_HOST=0.0.0.0
      - WEB-ANNO_SERVER_PORT=3000
      #networks:
    #  - traefik_net
    #labels:
    #  - traefik.enable=true
    #  - traefik.http.routers.web-anno.rule=Host(`web-anno.app.internal`)
#volumes:
#  data:

#networks:
#  traefik_net:
#    external: true

